safe:        true
auto:        true
base-url:    /
server:      true
server_port: 4000

title:       uComponents

lsi:         false
permalink:   pretty
pygments:    true
markdown:    maruku
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex
